---
driver_plugin: vagrant

platforms:
- name: ubuntu-12.10
  driver_config:
    box: canonical-ubuntu-12.10
    box_url: http://cloud-images.ubuntu.com/vagrant/quantal/current/quantal-server-cloudimg-amd64-vagrant-disk1.box
    require_chef_omnibus: true
    customize:
      cpus: 1
      memory: 1024
- name: ubuntu-12.04
  driver_config:
    box: canonical-ubuntu-12.04
    box_url: http://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-amd64-vagrant-disk1.box
    require_chef_omnibus: true
    customize:
      cpus: 1
      memory: 1024
- name: ubuntu-10.04
  driver_config:
    box: canonical-ubuntu-10.04
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-10.04_chef-11.2.0.box
    require_chef_omnibus: true
    customize:
      cpus: 1
      memory: 1024
- name: centos-6.3
  driver_config:
    box: opscode-centos-6.3
    box_url: http://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-6.3_chef-11.2.0.box
    customize:
      cpus: 1
      memory: 1024

suites:
- name: default
  run_list: ["redmine"]
  attributes:
    redmine:
      databases:
        production:
          password: "redmine_password"
      revision: "2.2.4"
    mysql:
      server_root_password: "supersecret_password"
      server_repl_password: "supersecret_password"
      server_debian_password: "supersecret_password"
    postgresql:
      password:
        postgres: "supersecret_password"
        
